CREATE TABLE IF NOT EXISTS users (

 id INTEGER PRIMARY KEY AUTOINCREMENT,

 name TEXT NOT NULL,

 email TEXT NOT NULL UNIQUE,

 password_hash TEXT NOT NULL,

 created_at DATETIME DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE IF NOT EXISTS journal_entries (

 id INTEGER PRIMARY KEY AUTOINCREMENT,

 user_id INTEGER NOT NULL,

 entry_date TEXT NOT NULL,

 activity TEXT NOT NULL,

 energy INTEGER,

 engagement INTEGER,

 notes TEXT,

 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

 FOREIGN KEY(user_id) REFERENCES users(id)

);
