CREATE TABLE IF NOT EXISTS users (

 id INTEGER PRIMARY KEY AUTOINCREMENT,

 name TEXT NOT NULL,

 email TEXT NOT NULL UNIQUE,

 password_hash TEXT NOT NULL,

 created_at DATETIME DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE IF NOT EXISTS journals (

 id INTEGER PRIMARY KEY AUTOINCREMENT,

 user_id INTEGER NOT NULL,

 name TEXT NOT NULL,

 template_type TEXT NOT NULL,

 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

 FOREIGN KEY(user_id) REFERENCES users(id)

);

CREATE TABLE IF NOT EXISTS journal_entries (

 id INTEGER PRIMARY KEY AUTOINCREMENT,

 user_id INTEGER NOT NULL,

 journal_id INTEGER,

 title TEXT,

 content TEXT,

 entry_date TEXT NOT NULL,

 activity TEXT NOT NULL,

 energy INTEGER,

 engagement INTEGER,

 notes TEXT,

 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

 FOREIGN KEY(user_id) REFERENCES users(id),

 FOREIGN KEY(journal_id) REFERENCES journals(id)

);
